name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: abbbi/github-actions-tune@0b48641ceb645d4ad4573b0d17b770d85770f9c7
    - uses: jetli/wasm-pack-action@f98777369a49686b132a9e8f0fdd59837bf3c3fd
      with:
        version: 'v0.10.0'
    - run: rustup component add rustfmt
    - run: rustup component add clippy
    - run: sudo apt-get install -y --no-install-recommends jq tidy
    - name: Build
      run: ./build.sh check
